services:
  - type: web
    name: devis-pdf-generator
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python create_default_logo.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    healthCheckPath: /health 